#!/bin/bash
# This script re-launches sbatch jobs for specific failed combinations.
# It targets only the cases where --no-keep_largest_only is used.
# Total number of jobs to be launched: 20

# --- Rerun Job 1: F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3 ---
sbatch -J F20204_Liver_Rerun_1 launcher_dgxtiny_textprompt.sh --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode minmax --use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode minmax --no-use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 95 --use_otsu --no-keep_largest_only --no-fill_holes"

# --- Rerun Job 2: F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3 ---
sbatch -J F20204_Liver_Rerun_2 launcher_dgxtiny_textprompt.sh --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 95 --no-use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 98 --use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 98 --no-use_otsu --no-keep_largest_only --no-fill_holes"

# --- Rerun Job 3: F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3 ---
sbatch -J F20204_Liver_Rerun_3 launcher_dgxtiny_textprompt.sh --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 99 --use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 99 --no-use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 95 --use_otsu --no-keep_largest_only --no-fill_holes"

# --- Rerun Job 4: F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3 ---
sbatch -J F20204_Liver_Rerun_4 launcher_dgxtiny_textprompt.sh --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 95 --no-use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 98 --use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 98 --no-use_otsu --no-keep_largest_only --no-fill_holes"

# --- Rerun Job 5: F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3 ---
sbatch -J F20204_Liver_Rerun_5 launcher_dgxtiny_textprompt.sh --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 99 --use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 99 --no-use_otsu --no-keep_largest_only --no-fill_holes"

# --- Rerun Job 6: F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3 ---
sbatch -J F20254_Liver_Rerun_1 launcher_dgxtiny_textprompt.sh --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode minmax --use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode minmax --no-use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 95 --use_otsu --no-keep_largest_only --no-fill_holes"

# --- Rerun Job 7: F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3 ---
sbatch -J F20254_Liver_Rerun_2 launcher_dgxtiny_textprompt.sh --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 95 --no-use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 98 --use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 98 --no-use_otsu --no-keep_largest_only --no-fill_holes"

# --- Rerun Job 8: F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3 ---
sbatch -J F20254_Liver_Rerun_3 launcher_dgxtiny_textprompt.sh --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 99 --use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 99 --no-use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 95 --use_otsu --no-keep_largest_only --no-fill_holes"

# --- Rerun Job 9: F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3 ---
sbatch -J F20254_Liver_Rerun_4 launcher_dgxtiny_textprompt.sh --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 95 --no-use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 98 --use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 98 --no-use_otsu --no-keep_largest_only --no-fill_holes"

# --- Rerun Job 10: F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3 ---
sbatch -J F20254_Liver_Rerun_5 launcher_dgxtiny_textprompt.sh --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 99 --use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 99 --no-use_otsu --no-keep_largest_only --no-fill_holes"

# --- Rerun Job 11: F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3 ---
sbatch -J F20259_Pancreas_Rerun_1 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode minmax --use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode minmax --no-use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 95 --use_otsu --no-keep_largest_only --no-fill_holes"

# --- Rerun Job 12: F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3 ---
sbatch -J F20259_Pancreas_Rerun_2 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 95 --no-use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 98 --use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 98 --no-use_otsu --no-keep_largest_only --no-fill_holes"

# --- Rerun Job 13: F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3 ---
sbatch -J F20259_Pancreas_Rerun_3 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 99 --use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 99 --no-use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 95 --use_otsu --no-keep_largest_only --no-fill_holes"

# --- Rerun Job 14: F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3 ---
sbatch -J F20259_Pancreas_Rerun_4 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 95 --no-use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 98 --use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 98 --no-use_otsu --no-keep_largest_only --no-fill_holes"

# --- Rerun Job 15: F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3 ---
sbatch -J F20259_Pancreas_Rerun_5 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 99 --use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 99 --no-use_otsu --no-keep_largest_only --no-fill_holes"

# --- Rerun Job 16: F20260_Pancreas_Images_gradient_echo_DICOM_H5v3 ---
sbatch -J F20260_Pancreas_Rerun_1 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode minmax --use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode minmax --no-use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 95 --use_otsu --no-keep_largest_only --no-fill_holes"

# --- Rerun Job 17: F20260_Pancreas_Images_gradient_echo_DICOM_H5v3 ---
sbatch -J F20260_Pancreas_Rerun_2 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 95 --no-use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 98 --use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 98 --no-use_otsu --no-keep_largest_only --no-fill_holes"

# --- Rerun Job 18: F20260_Pancreas_Images_gradient_echo_DICOM_H5v3 ---
sbatch -J F20260_Pancreas_Rerun_3 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 99 --use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 99 --no-use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 95 --use_otsu --no-keep_largest_only --no-fill_holes"

# --- Rerun Job 19: F20260_Pancreas_Images_gradient_echo_DICOM_H5v3 ---
sbatch -J F20260_Pancreas_Rerun_4 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 95 --no-use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 98 --use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 98 --no-use_otsu --no-keep_largest_only --no-fill_holes"

# --- Rerun Job 20: F20260_Pancreas_Images_gradient_echo_DICOM_H5v3 ---
sbatch -J F20260_Pancreas_Rerun_5 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 99 --use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 99 --no-use_otsu --no-keep_largest_only --no-fill_holes"
