#!/bin/bash
# This script launches sbatch jobs, with each job running 3 command combinations.
# Total number of jobs to be launched: 42

# --- Job 1: F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3 (1-3) ---
sbatch -J F20204_Liver_1 launcher_dgxtiny_textprompt.sh --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode minmax --use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode minmax --use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode minmax --use_otsu --keep_largest_only --no-fill_holes"

# --- Job 2: F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3 (4-6) ---
sbatch -J F20204_Liver_2 launcher_dgxtiny_textprompt.sh --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode minmax --no-use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode minmax --no-use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode minmax --no-use_otsu --keep_largest_only --no-fill_holes"

# --- Job 3: F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3 (7-9) ---
sbatch -J F20204_Liver_3 launcher_dgxtiny_textprompt.sh --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 95 --use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 95 --use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 95 --use_otsu --keep_largest_only --no-fill_holes"

# --- Job 4: F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3 (10-12) ---
sbatch -J F20204_Liver_4 launcher_dgxtiny_textprompt.sh --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 95 --no-use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 95 --no-use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 95 --no-use_otsu --keep_largest_only --no-fill_holes"

# --- Job 5: F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3 (13-15) ---
sbatch -J F20204_Liver_5 launcher_dgxtiny_textprompt.sh --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 98 --use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 98 --use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 98 --use_otsu --keep_largest_only --no-fill_holes"

# --- Job 6: F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3 (16-18) ---
sbatch -J F20204_Liver_6 launcher_dgxtiny_textprompt.sh --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 98 --no-use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 98 --no-use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 98 --no-use_otsu --keep_largest_only --no-fill_holes"

# --- Job 7: F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3 (19-21) ---
sbatch -J F20204_Liver_7 launcher_dgxtiny_textprompt.sh --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 99 --use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 99 --use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 99 --use_otsu --keep_largest_only --no-fill_holes"

# --- Job 8: F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3 (22-24) ---
sbatch -J F20204_Liver_8 launcher_dgxtiny_textprompt.sh --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 99 --no-use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 99 --no-use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 99 --no-use_otsu --keep_largest_only --no-fill_holes"

# --- Job 9: F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3 (25-27) ---
sbatch -J F20204_Liver_9 launcher_dgxtiny_textprompt.sh --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 95 --use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 95 --use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 95 --use_otsu --keep_largest_only --no-fill_holes"

# --- Job 10: F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3 (28-30) ---
sbatch -J F20204_Liver_10 launcher_dgxtiny_textprompt.sh --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 95 --no-use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 95 --no-use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 95 --no-use_otsu --keep_largest_only --no-fill_holes"

# --- Job 11: F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3 (31-33) ---
sbatch -J F20204_Liver_11 launcher_dgxtiny_textprompt.sh --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 98 --use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 98 --use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 98 --use_otsu --keep_largest_only --no-fill_holes"

# --- Job 12: F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3 (34-36) ---
sbatch -J F20204_Liver_12 launcher_dgxtiny_textprompt.sh --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 98 --no-use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 98 --no-use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 98 --no-use_otsu --keep_largest_only --no-fill_holes"

# --- Job 13: F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3 (37-39) ---
sbatch -J F20204_Liver_13 launcher_dgxtiny_textprompt.sh --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 99 --use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 99 --use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 99 --use_otsu --keep_largest_only --no-fill_holes"

# --- Job 14: F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3 (40-42) ---
sbatch -J F20204_Liver_14 launcher_dgxtiny_textprompt.sh --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 99 --no-use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 99 --no-use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20204_Liver_Imaging_T1_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 99 --no-use_otsu --keep_largest_only --no-fill_holes"

# --- Job 15: F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3 (1-3) ---
sbatch -J F20254_Liver_1 launcher_dgxtiny_textprompt.sh --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode minmax --use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode minmax --use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode minmax --use_otsu --keep_largest_only --no-fill_holes"

# --- Job 16: F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3 (4-6) ---
sbatch -J F20254_Liver_2 launcher_dgxtiny_textprompt.sh --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode minmax --no-use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode minmax --no-use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode minmax --no-use_otsu --keep_largest_only --no-fill_holes"

# --- Job 17: F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3 (7-9) ---
sbatch -J F20254_Liver_3 launcher_dgxtiny_textprompt.sh --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 95 --use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 95 --use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 95 --use_otsu --keep_largest_only --no-fill_holes"

# --- Job 18: F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3 (10-12) ---
sbatch -J F20254_Liver_4 launcher_dgxtiny_textprompt.sh --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 95 --no-use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 95 --no-use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 95 --no-use_otsu --keep_largest_only --no-fill_holes"

# --- Job 19: F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3 (13-15) ---
sbatch -J F20254_Liver_5 launcher_dgxtiny_textprompt.sh --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 98 --use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 98 --use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 98 --use_otsu --keep_largest_only --no-fill_holes"

# --- Job 20: F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3 (16-18) ---
sbatch -J F20254_Liver_6 launcher_dgxtiny_textprompt.sh --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 98 --no-use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 98 --no-use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 98 --no-use_otsu --keep_largest_only --no-fill_holes"

# --- Job 21: F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3 (19-21) ---
sbatch -J F20254_Liver_7 launcher_dgxtiny_textprompt.sh --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 99 --use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 99 --use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 99 --use_otsu --keep_largest_only --no-fill_holes"

# --- Job 22: F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3 (22-24) ---
sbatch -J F20254_Liver_8 launcher_dgxtiny_textprompt.sh --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 99 --no-use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 99 --no-use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 99 --no-use_otsu --keep_largest_only --no-fill_holes"

# --- Job 23: F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3 (25-27) ---
sbatch -J F20254_Liver_9 launcher_dgxtiny_textprompt.sh --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 95 --use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 95 --use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 95 --use_otsu --keep_largest_only --no-fill_holes"

# --- Job 24: F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3 (28-30) ---
sbatch -J F20254_Liver_10 launcher_dgxtiny_textprompt.sh --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 95 --no-use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 95 --no-use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 95 --no-use_otsu --keep_largest_only --no-fill_holes"

# --- Job 25: F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3 (31-33) ---
sbatch -J F20254_Liver_11 launcher_dgxtiny_textprompt.sh --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 98 --use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 98 --use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 98 --use_otsu --keep_largest_only --no-fill_holes"

# --- Job 26: F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3 (34-36) ---
sbatch -J F20254_Liver_12 launcher_dgxtiny_textprompt.sh --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 98 --no-use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 98 --no-use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 98 --no-use_otsu --keep_largest_only --no-fill_holes"

# --- Job 27: F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3 (37-39) ---
sbatch -J F20254_Liver_13 launcher_dgxtiny_textprompt.sh --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 99 --use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 99 --use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 99 --use_otsu --keep_largest_only --no-fill_holes"

# --- Job 28: F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3 (40-42) ---
sbatch -J F20254_Liver_14 launcher_dgxtiny_textprompt.sh --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 99 --no-use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 99 --no-use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20254_Liver_imaging_IDEAL_protocol_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 99 --no-use_otsu --keep_largest_only --no-fill_holes"

# --- Job 29: F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3 (1-3) ---
sbatch -J F20259_Pancreas_1 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode minmax --use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode minmax --use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode minmax --use_otsu --keep_largest_only --no-fill_holes"

# --- Job 30: F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3 (4-6) ---
sbatch -J F20259_Pancreas_2 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode minmax --no-use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode minmax --no-use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode minmax --no-use_otsu --keep_largest_only --no-fill_holes"

# --- Job 31: F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3 (7-9) ---
sbatch -J F20259_Pancreas_3 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 95 --use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 95 --use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 95 --use_otsu --keep_largest_only --no-fill_holes"

# --- Job 32: F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3 (10-12) ---
sbatch -J F20259_Pancreas_4 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 95 --no-use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 95 --no-use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 95 --no-use_otsu --keep_largest_only --no-fill_holes"

# --- Job 33: F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3 (13-15) ---
sbatch -J F20259_Pancreas_5 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 98 --use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 98 --use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 98 --use_otsu --keep_largest_only --no-fill_holes"

# --- Job 34: F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3 (16-18) ---
sbatch -J F20259_Pancreas_6 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 98 --no-use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 98 --no-use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 98 --no-use_otsu --keep_largest_only --no-fill_holes"

# --- Job 35: F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3 (19-21) ---
sbatch -J F20259_Pancreas_7 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 99 --use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 99 --use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 99 --use_otsu --keep_largest_only --no-fill_holes"

# --- Job 36: F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3 (22-24) ---
sbatch -J F20259_Pancreas_8 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 99 --no-use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 99 --no-use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 99 --no-use_otsu --keep_largest_only --no-fill_holes"

# --- Job 37: F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3 (25-27) ---
sbatch -J F20259_Pancreas_9 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 95 --use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 95 --use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 95 --use_otsu --keep_largest_only --no-fill_holes"

# --- Job 38: F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3 (28-30) ---
sbatch -J F20259_Pancreas_10 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 95 --no-use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 95 --no-use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 95 --no-use_otsu --keep_largest_only --no-fill_holes"

# --- Job 39: F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3 (31-33) ---
sbatch -J F20259_Pancreas_11 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 98 --use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 98 --use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 98 --use_otsu --keep_largest_only --no-fill_holes"

# --- Job 40: F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3 (34-36) ---
sbatch -J F20259_Pancreas_12 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 98 --no-use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 98 --no-use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 98 --no-use_otsu --keep_largest_only --no-fill_holes"

# --- Job 41: F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3 (37-39) ---
sbatch -J F20259_Pancreas_13 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 99 --use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 99 --use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 99 --use_otsu --keep_largest_only --no-fill_holes"

# --- Job 42: F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3 (40-42) ---
sbatch -J F20259_Pancreas_14 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 99 --no-use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 99 --no-use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20259_Pancreas_Images_ShMoLLI_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 99 --no-use_otsu --keep_largest_only --no-fill_holes"

# --- Job 43: F20260_Pancreas_Images_gradient_echo_DICOM_H5v3 (1-3) ---
sbatch -J F20260_Pancreas_1 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode minmax --use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode minmax --use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode minmax --use_otsu --keep_largest_only --no-fill_holes"

# --- Job 44: F20260_Pancreas_Images_gradient_echo_DICOM_H5v3 (4-6) ---
sbatch -J F20260_Pancreas_2 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode minmax --no-use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode minmax --no-use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode minmax --no-use_otsu --keep_largest_only --no-fill_holes"

# --- Job 45: F20260_Pancreas_Images_gradient_echo_DICOM_H5v3 (7-9) ---
sbatch -J F20260_Pancreas_3 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 95 --use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 95 --use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 95 --use_otsu --keep_largest_only --no-fill_holes"

# --- Job 46: F20260_Pancreas_Images_gradient_echo_DICOM_H5v3 (10-12) ---
sbatch -J F20260_Pancreas_4 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 95 --no-use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 95 --no-use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 95 --no-use_otsu --keep_largest_only --no-fill_holes"

# --- Job 47: F20260_Pancreas_Images_gradient_echo_DICOM_H5v3 (13-15) ---
sbatch -J F20260_Pancreas_5 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 98 --use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 98 --use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 98 --use_otsu --keep_largest_only --no-fill_holes"

# --- Job 48: F20260_Pancreas_Images_gradient_echo_DICOM_H5v3 (16-18) ---
sbatch -J F20260_Pancreas_6 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 98 --no-use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 98 --no-use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 98 --no-use_otsu --keep_largest_only --no-fill_holes"

# --- Job 49: F20260_Pancreas_Images_gradient_echo_DICOM_H5v3 (19-21) ---
sbatch -J F20260_Pancreas_7 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 99 --use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 99 --use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 99 --use_otsu --keep_largest_only --no-fill_holes"

# --- Job 50: F20260_Pancreas_Images_gradient_echo_DICOM_H5v3 (22-24) ---
sbatch -J F20260_Pancreas_8 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 99 --no-use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 99 --no-use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 99 --no-use_otsu --keep_largest_only --no-fill_holes"

# --- Job 51: F20260_Pancreas_Images_gradient_echo_DICOM_H5v3 (25-27) ---
sbatch -J F20260_Pancreas_9 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 95 --use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 95 --use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 95 --use_otsu --keep_largest_only --no-fill_holes"

# --- Job 52: F20260_Pancreas_Images_gradient_echo_DICOM_H5v3 (28-30) ---
sbatch -J F20260_Pancreas_10 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 95 --no-use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 95 --no-use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 95 --no-use_otsu --keep_largest_only --no-fill_holes"

# --- Job 53: F20260_Pancreas_Images_gradient_echo_DICOM_H5v3 (31-33) ---
sbatch -J F20260_Pancreas_11 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 98 --use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 98 --use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 98 --use_otsu --keep_largest_only --no-fill_holes"

# --- Job 54: F20260_Pancreas_Images_gradient_echo_DICOM_H5v3 (34-36) ---
sbatch -J F20260_Pancreas_12 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 98 --no-use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 98 --no-use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 98 --no-use_otsu --keep_largest_only --no-fill_holes"

# --- Job 55: F20260_Pancreas_Images_gradient_echo_DICOM_H5v3 (37-39) ---
sbatch -J F20260_Pancreas_13 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 99 --use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 99 --use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 99 --use_otsu --keep_largest_only --no-fill_holes"

# --- Job 56: F20260_Pancreas_Images_gradient_echo_DICOM_H5v3 (40-42) ---
sbatch -J F20260_Pancreas_14 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 99 --no-use_otsu --no-keep_largest_only --no-fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 99 --no-use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 99 --no-use_otsu --keep_largest_only --no-fill_holes"
