#!/bin/bash
# This script launches sbatch jobs, with each job running 3 command combinations.
# Total number of jobs to be launched: 42

# --- Job 29: F20260_Pancreas_Images_gradient_echo_DICOM_H5v3 (1-3) ---
sbatch -J F20260_Pancreas_1 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode minmax --use_otsu --no-keep_largest_only; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode minmax --use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode minmax --use_otsu --keep_largest_only --no-fill_holes"

# --- Job 30: F20260_Pancreas_Images_gradient_echo_DICOM_H5v3 (4-6) ---
sbatch -J F20260_Pancreas_2 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode minmax --no-use_otsu --no-keep_largest_only; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode minmax --no-use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode minmax --no-use_otsu --keep_largest_only --no-fill_holes"

# --- Job 31: F20260_Pancreas_Images_gradient_echo_DICOM_H5v3 (7-9) ---
sbatch -J F20260_Pancreas_3 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 95 --use_otsu --no-keep_largest_only; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 95 --use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 95 --use_otsu --keep_largest_only --no-fill_holes"

# --- Job 32: F20260_Pancreas_Images_gradient_echo_DICOM_H5v3 (10-12) ---
sbatch -J F20260_Pancreas_4 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 95 --no-use_otsu --no-keep_largest_only; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 95 --no-use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 95 --no-use_otsu --keep_largest_only --no-fill_holes"

# --- Job 33: F20260_Pancreas_Images_gradient_echo_DICOM_H5v3 (13-15) ---
sbatch -J F20260_Pancreas_5 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 98 --use_otsu --no-keep_largest_only; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 98 --use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 98 --use_otsu --keep_largest_only --no-fill_holes"

# --- Job 34: F20260_Pancreas_Images_gradient_echo_DICOM_H5v3 (16-18) ---
sbatch -J F20260_Pancreas_6 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 98 --no-use_otsu --no-keep_largest_only; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 98 --no-use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 98 --no-use_otsu --keep_largest_only --no-fill_holes"

# --- Job 35: F20260_Pancreas_Images_gradient_echo_DICOM_H5v3 (19-21) ---
sbatch -J F20260_Pancreas_7 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 99 --use_otsu --no-keep_largest_only; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 99 --use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 99 --use_otsu --keep_largest_only --no-fill_holes"

# --- Job 36: F20260_Pancreas_Images_gradient_echo_DICOM_H5v3 (22-24) ---
sbatch -J F20260_Pancreas_8 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 99 --no-use_otsu --no-keep_largest_only; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 99 --no-use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 1 --window_max_percentile 99 --no-use_otsu --keep_largest_only --no-fill_holes"

# --- Job 37: F20260_Pancreas_Images_gradient_echo_DICOM_H5v3 (25-27) ---
sbatch -J F20260_Pancreas_9 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 95 --use_otsu --no-keep_largest_only; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 95 --use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 95 --use_otsu --keep_largest_only --no-fill_holes"

# --- Job 38: F20260_Pancreas_Images_gradient_echo_DICOM_H5v3 (28-30) ---
sbatch -J F20260_Pancreas_10 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 95 --no-use_otsu --no-keep_largest_only; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 95 --no-use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 95 --no-use_otsu --keep_largest_only --no-fill_holes"

# --- Job 39: F20260_Pancreas_Images_gradient_echo_DICOM_H5v3 (31-33) ---
sbatch -J F20260_Pancreas_11 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 98 --use_otsu --no-keep_largest_only; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 98 --use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 98 --use_otsu --keep_largest_only --no-fill_holes"

# --- Job 40: F20260_Pancreas_Images_gradient_echo_DICOM_H5v3 (34-36) ---
sbatch -J F20260_Pancreas_12 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 98 --no-use_otsu --no-keep_largest_only; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 98 --no-use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 98 --no-use_otsu --keep_largest_only --no-fill_holes"

# --- Job 41: F20260_Pancreas_Images_gradient_echo_DICOM_H5v3 (37-39) ---
sbatch -J F20260_Pancreas_13 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 99 --use_otsu --no-keep_largest_only; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 99 --use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 99 --use_otsu --keep_largest_only --no-fill_holes"

# --- Job 42: F20260_Pancreas_Images_gradient_echo_DICOM_H5v3 (40-42) ---
sbatch -J F20260_Pancreas_14 launcher_dgxtiny_textprompt.sh --programme minipipes/textprompt_pan.py --args "--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 99 --no-use_otsu --no-keep_largest_only; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 99 --no-use_otsu --keep_largest_only --fill_holes; \
--input_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/exported_images/NIFTI/ --output_dir /group/glastonbury/soumick/dataset/ukbbnii/minisets/F20260_Pancreas_Images_gradient_echo_DICOM_H5v3/segmentations/MedSAM_textprompt/ --norm_mode window --window_min_percentile 5 --window_max_percentile 99 --no-use_otsu --keep_largest_only --no-fill_holes"
